// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBarzc3A0TQVUjN7lq62FnVoFfb2KCODmg',
    appId: '1:244449345510:web:4c90b7bb43302fb8c56027',
    messagingSenderId: '244449345510',
    projectId: 'media9-2f1ab',
    authDomain: 'media9-2f1ab.firebaseapp.com',
    storageBucket: 'media9-2f1ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBskqyBk8H9J8cShhwBaLa0AaR2r3bEPX8',
    appId: '1:244449345510:android:6c09f8c308028eb0c56027',
    messagingSenderId: '244449345510',
    projectId: 'media9-2f1ab',
    storageBucket: 'media9-2f1ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbmUuD5vqQubOqR01O-_qDc7oNEL9nV_4',
    appId: '1:244449345510:ios:fe273c78c4ec0b3ec56027',
    messagingSenderId: '244449345510',
    projectId: 'media9-2f1ab',
    storageBucket: 'media9-2f1ab.appspot.com',
    iosBundleId: 'com.media9newsnetwork.media9',
  );
}
